services:
  api:
    build: .
    depends_on:
      - postgres  # depends on to make sure to start the database container first
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app/:ro
    # env_file:
    #   - "./.env"
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=267766ks
      - DATABASE_NAME=fastapi
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
    
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=267766ks
      - POSTGRES_USERNAME=postgres

    volumes:
      - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db:
